In [11]:
import pandas as pd
import arabic
import pyarabic
import helpers
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
#########################
from numpy import array, argmax
import numpy as np
import re
##########################

In [46]:
old_data_flag = 1 # 1 only if old data, 0 otherwise

In [47]:
if (old_data_flag == 1):
    data = pd.read_csv('All_OldData_cleaned.csv',encoding='utf-8', index_col=0)
    print("working into old data sample ")
    cols = [1,2,4]
    data.drop(data.columns[cols], axis=1,inplace=True)
    data.columns = [u'البيت',u'البحر']
    our_alphabets = "".join(arabic.alphabet) + "".join(arabic.tashkeel)+" "
    our_alphabets = "".join(our_alphabets)
    data[u'البيت'] = data[u'البيت'].apply(lambda x: re.sub(u'(^'+our_alphabets+')',u'',x)).apply(lambda x: re.sub(u'  *',u" ",x)).apply(lambda x: re.sub(u'ّ+', u'ّ', x)).apply(lambda x: x.strip())
    data[u'البيت'] = data[u'البيت'].apply(pyarabic.araby.strip_tashkeel).apply(pyarabic.araby.strip_tatweel)
elif (old_data_flag == 0):
    print("working on new data sample")
    data = pd.read_csv('All_NewData_cleaned.csv', encoding='utf-8',index_col=0)
    bahr = u'البحر'
    bayt = u'البيت'
    data  = data[[bayt, bahr]]
    our_alphabets = "".join(arabic.alphabet) + "".join(arabic.tashkeel)+" "
    our_alphabets = "".join(our_alphabets)
    data[u'البيت'] = data[u'البيت'].apply(lambda x: re.sub(u'(^'+our_alphabets+')',u'',x)).apply(lambda x: re.sub(u'  *',u" ",x)).apply(lambda x: re.sub(u'ّ+', u'ّ', x)).apply(lambda x: x.strip())
    data[u'البيت'] = data[u'البيت'].apply(pyarabic.araby.strip_tashkeel).apply(pyarabic.araby.strip_tatweel)

working into old data sample 


In [48]:
data.columns

Index([u'العصر', u'الشاعر', u'الديوان', u'القافية', u'البحر', u'الشطر الايسر',
       u'الشطر الايمن', u'البيت'],
      dtype='object')

In [49]:
bahr = u'البحر'
bayt = u'البيت'
data  = data[[bayt, bahr]]
data.shape

(1000, 2)

In [50]:
data.iloc[:, 1].value_counts()

الطويل      291
الوافر      208
المتقارب    158
الكامل      146
البسيط      101
الخفيف       50
الرجز        13
السريع       13
المنسرح      11
الرمل         9
Name: البحر, dtype: int64

# Getting Unique Bohor

In [53]:
classic_bohor = list(data[u'البحر'].unique()[0:11])
for i in classic_bohor:
    print i

الطويل
المنسرح
المتقارب
الخفيف
الكامل
السريع
الوافر
الرجز
البسيط
الرمل


# Filtering Data

In [67]:
# some_values = [u'البسيط',u'الخفيف',u'السريع',u'الرمل',u'الوافر',u'الكامل',u'الرجز',u'الطويل']
# filtered_data = data.loc[data[u'البحر'].isin(some_values)]
filtered_data = data.loc[data[u'البحر'].isin(classic_bohor)]
filtered_data.iloc[:, 1].value_counts()
filtered_data

البيت   البحر
0    خليلي لا تستعجلا أن تزودا وأن تجمعا شملي وتنتظ...  الطويل
1    فما لبث يوما بسابق مغنم ولا سرعتي يوما بسابقة ...  الطويل
2    وإن تنظراني اليوم أقض لبانة وتستوجبا منا علي و...  الطويل
3       لعمرك ما نفس بجد رشيدة تؤامرني سرا لأصرم مرثدا  الطويل
4    وإن ظهرت منه قوارص جمة وأفرع في لومي مرارا وأصعدا  الطويل
5    على غير ذنب أن أكون جنيته سوى قول باغ كادني فت...  الطويل
6    لعمري لنعم المرء تدعو بحبله إذا ما المنادي في ...  الطويل
7    عظيم رماد القدر لا متعبس ولا مؤيس منها إذا هو ...  الطويل
8    وإن صرحت كحل وهبت عرية من الريح لم تترك لذي ال...  الطويل
9    صبرت على وطء الموالي وحطمهم إذا ضن ذو القربى ع...  الطويل
10   ولم يحم فرج الحي إلا محافظ كريم المحيا ماجد غي...  الطويل
11   أرى جارتي خفت وخف نصيحها وحب بها لولا النوى وط...  الطويل
12   فبيني على نجم شخيس نحوسه وأشأم طير الزاجرين سن...  الطويل
13   فإن تشغبي فالشغب مني سجية إذا شيمتي لم يؤت منه...  الطويل
14   أقارض أقواما فأوفي قروضهم وعف إذا أردى النفوس ...  الطويل
15   على أن قومي أشقذوني فأصبحت دياري بأرض غير دان ...  الطويل
16     تنفذ منهم نافذات فسؤنني وأضمر أضغانا علي كشوحها  الطويل
17   فقلت فراق الدار أجمل بيننا وقد ينتئي عن دار سو...  الطويل
18   على أنني قد أدعي بأبيهم إذا عمت الدعوى وثاب صر...  الطويل
19   وأني أرى ديني يوافق دينهم إذا نسكوا أفراعها وذ...  الطويل
20   ومنزلة بالحج أخرى عرفتها لها بقعة لا يستطاع بر...  الطويل
21   بودك ما قومي على أن تركتهم سليمى إذا هبت شمال ...  الطويل
22   إذا النجم أمسى مغرب الشمس رائبا ولم يك برق في ...  الطويل
23   وغاب شعاع الشمس في غير جلبة ولا غمرة إلا وشيكا...  الطويل
24      وهاج عماء مقشعر كأنه نقيلة نعل بان منها سريحها  الطويل
25   إذا عدم المحلوب عادت عليهم قدور كثير في القصاع...  الطويل
26   يثوب إليها كل ضيف وجانب كما رد دهداه القلاص نض...  الطويل
27     بأيديهم مقرومة ومغالق يعود بأرزاق العيال منيحها  الطويل
28   وملمومة لا يخرق الطرف عرضها لها كوكب فخم شديد ...  الطويل
29   تسير وتزجي السم تحت نحورها كريه إلى من فاجأته ...  الطويل
..                                                 ...     ...
970  أناس إذا لاقوا عدى فكأنما سلاح الذي لاقوا غبار...  الطويل
971  رموا بنواصيها القسي فجئنها دوامي الهوادي سالما...  الطويل
972  أولئك أحلى من حياة معادة وأكثر ذكرا من دهور ال...  الطويل
973  نصرت عليا يا ابنه ببواتر من الفعل لا فل لها في...  الطويل
974   وأبهر آيات التهامي أنه أبوك وأجدى مالكم من مناقب  الطويل
975  إذا لم تكن نفس النسيب كأصله فماذا الذي تغني كر...  الطويل
976  وما قربت أشباه قوم أباعد ولا بعدت أشباه قوم أقارب  الطويل
977    إذا علوي لم يكن مثل طاهر فما هو إلا حجة للنواصب  الطويل
978  يقولون تأثير الكواكب في الورى فما باله تأثيره ...  الطويل
979  علا كتد الدنيا إلى كل غاية تسير به سير الذلول ...  الطويل
980  وحق له أن يسبق الناس جالسا ويدرك مالم يدركوا غ...  الطويل
981  ويحذى عرانين الملوك وإنها لمن قدميه في أجل الم...  الطويل
982  يد للزمان الجمع بيني وبينه لتفريقه بيني وبين ا...  الطويل
983  هو ابن رسول الله وابن وصيه وشبههما شبهت بعد ال...  الطويل
984  يرى أن ما ما بان منك لضارب بأقتل مما بان منك ل...  الطويل
985  ألا أيها المال الذي قد أباده تعز فهذا فعله في ...  الطويل
986  لعلك في وقت شغلت فؤاده عن الجود أو كثرت جيش محارب  الطويل
987  حملت إليه من لساني حديقة سقاها الحجى سقي الريا...  الطويل
988  فحييت خير ابن لخير أب بها لأشرف بيت في لؤي بن ...  الطويل
989  من الجآذر في زي الأعاريب حمر الحلى والمطايا وا...  البسيط
990  إن كنت تسأل شكا في معارفها فمن بلاك بتسهيد وتعذيب  البسيط
991  لا تجزني بضنا بي بعدها بقر تجزي دموعي مسكوبا ب...  البسيط
992     سوائر ربما سارت هوادجها منيعة بين مطعون ومضروب  البسيط
993  وربما وخدت أيدي المطي بها على نجيع من الفرسان ...  البسيط
994  كم زورة لك في الأعراب خافية أدهى وقد رقدوا من ...  البسيط
995  أزورهم وسواد الليل يشفع لي وأنثني وبياض الصبح ...  البسيط
996  قد وافقوا الوحش في سكنى مراتعها وخالفوها بتقوي...  البسيط
997   جيرانها وهم شر الجوار لها وصحبها وهم شر الأصاحيب  البسيط
998     فؤاد كل محب في بيوتهم ومال كل أخيذ المال محروب  البسيط
999  ما أوجه الحضر المستحسنات به كأوجه البدويات الر...  البسيط

[1000 rows x 2 columns]

In [57]:
# TESTING
print("Number of bohor : "+str(len(filtered_data[u'البحر'].unique())))
for i in filtered_data[u'البحر'].unique():
    print(i)
print(filtered_data.iloc[:, 1].value_counts())

Number of bohor : 10
الطويل
المنسرح
المتقارب
الخفيف
الكامل
السريع
الوافر
الرجز
البسيط
الرمل
الطويل      291
الوافر      208
المتقارب    158
الكامل      146
البسيط      101
الخفيف       50
الرجز        13
السريع       13
المنسرح      11
الرمل         9
Name: البحر, dtype: int64


In [58]:
filtered_data[0:10]

البيت   البحر
0  خليلي لا تستعجلا أن تزودا وأن تجمعا شملي وتنتظ...  الطويل
1  فما لبث يوما بسابق مغنم ولا سرعتي يوما بسابقة ...  الطويل
2  وإن تنظراني اليوم أقض لبانة وتستوجبا منا علي و...  الطويل
3     لعمرك ما نفس بجد رشيدة تؤامرني سرا لأصرم مرثدا  الطويل
4  وإن ظهرت منه قوارص جمة وأفرع في لومي مرارا وأصعدا  الطويل
5  على غير ذنب أن أكون جنيته سوى قول باغ كادني فت...  الطويل
6  لعمري لنعم المرء تدعو بحبله إذا ما المنادي في ...  الطويل
7  عظيم رماد القدر لا متعبس ولا مؤيس منها إذا هو ...  الطويل
8  وإن صرحت كحل وهبت عرية من الريح لم تترك لذي ال...  الطويل
9  صبرت على وطء الموالي وحطمهم إذا ضن ذو القربى ع...  الطويل

In [59]:
filtered_data[u'البيت'] = filtered_data[u'البيت'].apply(pyarabic.araby.strip_tatweel)
#filtered_data = filtered_data.apply(pyarabic.araby.strip_tatweel)

In [61]:
import h5py

def save(nameOfFile,nameOfDataset,dataVar):
    h5f = h5py.File(nameOfFile, 'w')
    h5f.create_dataset(nameOfDataset, data=dataVar)
    h5f.close()


/usr/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


# Encoding Bohor

In [68]:
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(list(filtered_data[u"البحر"]))
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
bohor_encoded = onehot_encoder.fit_transform(integer_encoded)

In [70]:
for i in some_values:
    print i

البسيط
الخفيف
السريع
الرمل
الوافر
الكامل
الرجز
الطويل


In [71]:
bohor_encoded[150000]
integer_encoded[150000]

IndexError: index 150000 is out of bounds for axis 0 with size 1000

In [ ]:
filtered_data.iloc[150000]

In [72]:
print(bohor_encoded.shape)
print(bohor_encoded)
#save('Y_Meters_Without_LowerClasses_OldData.h5', 'Y', bohor_encoded)

type(bohor_encoded)

(1000, 10)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


numpy.ndarray

# Encoding Abyat

In [73]:
#data_without_Tashkeel = filtered_data['البيت'].apply(pyarabic.araby.strip_tashkeel)
data_with_Tashkeel = filtered_data[u'البيت']

In [74]:
data_with_Tashkeel

0      خليلي لا تستعجلا أن تزودا وأن تجمعا شملي وتنتظ...
1      فما لبث يوما بسابق مغنم ولا سرعتي يوما بسابقة ...
2      وإن تنظراني اليوم أقض لبانة وتستوجبا منا علي و...
3         لعمرك ما نفس بجد رشيدة تؤامرني سرا لأصرم مرثدا
4      وإن ظهرت منه قوارص جمة وأفرع في لومي مرارا وأصعدا
5      على غير ذنب أن أكون جنيته سوى قول باغ كادني فت...
6      لعمري لنعم المرء تدعو بحبله إذا ما المنادي في ...
7      عظيم رماد القدر لا متعبس ولا مؤيس منها إذا هو ...
8      وإن صرحت كحل وهبت عرية من الريح لم تترك لذي ال...
9      صبرت على وطء الموالي وحطمهم إذا ضن ذو القربى ع...
10     ولم يحم فرج الحي إلا محافظ كريم المحيا ماجد غي...
11     أرى جارتي خفت وخف نصيحها وحب بها لولا النوى وط...
12     فبيني على نجم شخيس نحوسه وأشأم طير الزاجرين سن...
13     فإن تشغبي فالشغب مني سجية إذا شيمتي لم يؤت منه...
14     أقارض أقواما فأوفي قروضهم وعف إذا أردى النفوس ...
15     على أن قومي أشقذوني فأصبحت دياري بأرض غير دان ...
16       تنفذ منهم نافذات فسؤنني وأضمر أضغانا علي كشوحها
17     فقلت فراق الدار أجمل بين

In [75]:
data_with_Tashkeel.shape

(1000,)

In [76]:
maximum_bayt_len = np.max((data_with_Tashkeel.apply(helpers.separate_token_with_dicrites).apply(len)))
maximum_bayt_len

62

In [77]:
#encoded_byot = data_with_Tashkeel.apply(lambda x: helpers.string_with_tashkeel_vectorizer(x, maximum_bayt_len))
encoded_byot = data_with_Tashkeel.apply(lambda x: helpers.string_with_tashkeel_vectorizer_OneHot(x, maximum_bayt_len))
len(encoded_byot[1])


62

In [78]:
encoded_byot[1].shape

(62, 183)

In [79]:
encoded_byot[1]
encoded_byot.shape
print(data_with_Tashkeel[100])

على أن قومي أسلموني وعرتي وقوم الفتى أظفاره ودعائمه


In [80]:
# Reshaping the heck!!
reshaped_data_matrix_with_tashkeel = np.stack(encoded_byot, axis=0)
#reshaped_data_matrix_without_tashkeel = np.stack(encoded_byot[0:1000000], axis=0)

In [81]:
# Dimensions
reshaped_data_matrix_with_tashkeel

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

# Saving Abyat

In [ ]:
save('old_data_matrix_with_tashkeel_OneHotEncodingWithTashkeel.h5', 'X', reshaped_data_matrix_with_tashkeel)

In [82]:
encoded_byot.shape

(1000,)

In [83]:
X = np.array(encoded_byot)
X[1].shape

(62, 183)

In [84]:
nono = encoded_byot.as_matrix()
np.stack(nono)

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [85]:
test = encoded_byot

In [86]:
test = test[0:2]
test

0    [[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,...
1    [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
Name: البيت, dtype: object

In [87]:
resualt = np.stack(test, axis=0)
print(resualt.shape)
print(resualt)

(2, 62, 183)
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 1 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [ ]:
bayt_encoded_without_tashkeel

In [ ]:
import helpers 
import pandas as pd

In [ ]:
d = pd.read_csv('../../../data/All_clean_data.csv')

In [ ]:
helpers.Clean_data(d,84)

In [ ]:
import helpers
import pandas as pd

In [ ]:
dd = pd.read_csv('../../../data/All_clean_data.csv')

In [ ]:
a = helpers.Clean_data(dd,84)