In [1]:
import pandas as pd
import arabic
import pyarabic
import helpers
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
#########################
from numpy import array, argmax
import numpy as np
import re
##########################

In [2]:
old_data_flag = 1 # 1 only if old data, 0 otherwise

In [3]:
if (old_data_flag == 1):
    data = pd.read_csv('All_OldData_cleaned.csv', index_col=0)
    print("working into old data sample ")
    cols = [1,2,4]
    data.drop(data.columns[cols], axis=1,inplace=True)
    data.columns = ['البيت', 'البحر']
    our_alphabets = "".join(arabic.alphabet) + "".join(arabic.tashkeel)+" "
    our_alphabets = "".join(our_alphabets)
    data['البيت'] = data['البيت'].apply(lambda x: re.sub(r'[^'+our_alphabets+']','',str(x))).apply(lambda x: re.sub(r'  *'," ",x)).apply(lambda x: re.sub(r'ّ+', 'ّ', x)).apply(lambda x: x.strip())
    #data['البيت'] = data['البيت'].apply(pyarabic.araby.strip_tashkeel).apply(pyarabic.araby.strip_tatweel)
elif (old_data_flag == 0):
    print("working on new data sample")
    data = pd.read_csv('All_NewData_cleaned.csv', index_col=0)
    bahr = 'البحر'
    bayt = 'البيت'
    data  = data[[bayt, bahr]]
    our_alphabets = "".join(arabic.alphabet) + "".join(arabic.tashkeel)+" "
    our_alphabets = "".join(our_alphabets)
    data['البيت'] = data['البيت'].apply(lambda x: re.sub(r'[^'+our_alphabets+']','',str(x))).apply(lambda x: re.sub(r'  *'," ",x)).apply(lambda x: re.sub(r'ّ+', 'ّ', x)).apply(lambda x: x.strip())
    #data['البيت'] = data['البيت'].apply(pyarabic.araby.strip_tashkeel).apply(pyarabic.araby.strip_tatweel)


working into old data sample 


In [4]:
data.columns

Index(['البيت', 'البحر'], dtype='object')

In [5]:
bahr = 'البحر'
bayt = 'البيت'
data  = data[[bayt, bahr]]
data.shape

(227615, 2)

In [6]:
data.iloc[:, 1].value_counts()

الطويل      68601
الكامل      50574
البسيط      37003
الوافر      23238
الخفيف      17984
السريع       9075
الرجز        7638
الرمل        6662
المنسرح      4375
المجتث       2085
المتدارك      380
Name: البحر, dtype: int64

# Getting Unique Bohor

In [7]:
classic_bohor = list(data.البحر.unique()[0:11])
classic_bohor

['البسيط',
 'الخفيف',
 'المجتث',
 'المتدارك',
 'السريع',
 'الرمل',
 'الوافر',
 'الكامل',
 'المنسرح',
 'الرجز',
 'الطويل']

# Filtering Data

In [8]:
#some_values = ['البسيط','الخفيف','السريع','الرمل','الوافر','الكامل','الرجز','الطويل']
#filtered_data = data.loc[data['البحر'].isin(some_values)]
filtered_data = data.loc[data['البحر'].isin(classic_bohor)]
filtered_data.iloc[:, 1].value_counts()
filtered_data

البيت   البحر
0       حاشا اهتمامك من إسداء مكرمة وأن يرى لك بين الن...  البسيط
1       دع مقصراً ليس بدَّاعاً ولا عجبٌ للأريحية والإح...  البسيط
2       أَيَّتُها النَفسُ لا تُهالي شَرخي قَد مَرَّ وَ...  البسيط
3       لَم يَبقَ إِلّا شَفاً يَسيرٌ قَرَّبَ مِن مَورِ...  البسيط
4       وَاِبتَهَلَ الدَهرُ في أَذاتي وَكانَ في الباطِ...  البسيط
5       وَأُمُّ دَفرٍ فَتاةُ سوءٍ تَخبُؤُني في ثَرىً م...  البسيط
6       مُرسِلَةً غارَةً بِخَيلٍ قَد غَنِيَت عَن هَبٍ ...  البسيط
7       وَجَدتُ حُبّي لَها قَديماً وَقَد تَبَيَّنتُ مَ...  البسيط
8       من سَرَّهُ كسبُ مالٍ لا نفاذَ له وراحةٌ قُرِنت...  البسيط
9       فلا يَمُدَّنَّ عينيه إلى سبب سوى القَناعة من م...  البسيط
10      فيال لها رتبة جَلَّت بلا طلبٍ ولا حسود ولا ذل ...  البسيط
11      إن الخليط أجدِّ البين فابتكروا لنية ثم ما عاجو...  البسيط
12      زمّوا الجمال وقالوا إن مشربكم ماء بكيلة لا ملح...  البسيط
13      ما كان بينهم إلا مجاهرة أشفقت منها فماذا زادك ...  البسيط
14      استقبلوا المسقط الشرقي يحفزهم في السير أشوَس م...  البسيط
15       كأن ظعنهم والآل يرفعها نخل المشقر أو ما زينت هجر  البسيط
16      ما زلت أرمقهم في الال مرتفعا حتى تقطع دون الجي...  البسيط
17      فاقر الهموم التي نامت مذكرة وشواشة سرحاً في دن...  البسيط
18      تذري الحصى وشماً من تحت منسمها كما يرض سواديَ ...  البسيط
19      تمر جتلاً على الحاذين ذا خصل كالعذق لا كشف فيه...  البسيط
20      كأن أوب ذراعيها إذا نجدت وأحرز الظل في أعدائه ...  البسيط
21      أوبُ ذراعي لجوج جاد واحدها حتى إذا ما انتهى أو...  البسيط
22      فأبلغن قومنا إن جئتهم عذراً عنا وهل ينفعنهم عن...  البسيط
23      أنا نذكرهم باللَه واحدة وبالقرابة والأخرى التي...  البسيط
24      حسن البلاء وأياماً لنا سلفت يبيَضُّ منها إذا م...  البسيط
25      فلا تعدوا علينا الزور وارتدعوا فإن عندكم من مس...  البسيط
26      لا تبطروا السلم واستأنوا بإخوتكم ان الندامة تع...  البسيط
27      وإن فينا صبوحاً غير ممتزج يصري الدماء عليه الص...  البسيط
28      فينا فتوّ وفينا سادة حشد عند الصباح وفينا جامل...  البسيط
29      كم من رئيس فريناه بأجمعه بالمشرفية حتى يعدل الصعر  البسيط
...                                                   ...     ...
227585  فأَذكَى صباباتٍ تقادَمَ عهدُها بأهلِ الحِمى حي...  الطويل
227586  وأشتاقُ أيامَ الدنوَّ فهل أَرى زمانَ التداني ب...  الطويل
227587  وما لغليلِ الشوقِ إلا دنوُّه دواءٌ إذا جمرُ ال...  الطويل
227588  وما شوقُ ورقٍ غابَ عنها هديلُها وقد كانَ ما بي...  الطويل
227589  تنوحُ سُحَيراً في الغصونِ كأنَّما لها عَذَبُ ا...  الطويل
227590  فتصدعُ قلبي حينَ تصدحُ سُحرةً وقد حلَّ أهلُ ال...  الطويل
227591  كشوقي إلى جيرانِ سَلْعٍ وحاجرٍ واِنْ ضيَّعوا س...  الطويل
227592  وهَجْلٍ به تُنضَى القَطا الكُدْرُ جُبْتُهُ بأع...  الطويل
227593  اخوضُ به لُجَّ العساقيلِ بعدَ ما شقتُ به نحوَ ...  الطويل
227594  يُجاذِبني فضلَ الجديلِ وقد غدتْ عياءً بُنيّاتُ...  الطويل
227595  يَطُسنَ بركبانِ الغرامِ على الوَجا الى جيرةٍ ب...  الطويل
227596  فأغدو على ظهرِ المطيَّةِ ساجداً مِن الأينِ ما ...  الطويل
227597  الى أن أرى شمساً شهيّاً بزوغُها مِن الحيَّ أو ...  الطويل
227598  وكم ليلةٍ قد بتُّ ارعى نجومَها وقد حَسَدَتْ عي...  الطويل
227599  أُساهرُ ديجورِها النجمَ حائراً وأهجرُ في ظَلْم...  الطويل
227600  غراماً بوجهٍ لو بدا من خبائه رأيتَ له نوراً عل...  الطويل
227601  يعودُ له بدرُ السماءِ إذا بدا له ورآه خاسئَ ال...  الطويل
227602  وما روضةٌ قد وشَّحَتْها يدُ الحيا بدمعِ سحابٍ ...  الطويل
227603  فاصبحَ فيها النَّورُ يَبسِمُ ثغرُه وفاحَ بها ع...  الطويل
227604  بأحسنَ مِن شعري وأين كمثلِه جواهرُ من لفظٍ تُح...  الطويل
227605  يُحيَّرُ ربَّ المنطقِ الجزلِ لفظُه فيصبحُ مِن ...  الطويل
227606  تراه على ذاكَ الترفُّعِ نادماً اِذا حطَّهُ شعر...  الطويل
227607  ويغدو وما بينَ الأضالِعِ جذوةٌ على الشعرِ نظمي...  الطويل
227608  إِذا ما هَتَفنا هَتفَةً في نَدِيِّنا أَتانا ال...  الطويل
227609  كَريمٌ يَغُضُّ الطَرفَ فَضلَ حَيائِهِ وَيَدنو ...  الطويل
227610  وَكَالسَيفِ إِن لايَنتَهُ لانَ مَسُّهُ وَحَدّا...  الطويل
227611  وَلي صاحِبٌ ما خفت مِن جَورِ حادِثٍ مِنَ الدَه...  الطويل
227612  إِذا عَضَّني صَرفُ الزَمانِ فَإِنَّني بِراياتِ...  الطويل
227613  أتيت لمصر في كتاب شفاعة إلى ولدٍ من والدٍ مورث...  الطويل
227614  فيا لكتاب جاءَ من 

In [9]:
# TESTING
print("Number of bohor : "+str(len(filtered_data.البحر.unique())))
print(filtered_data.البحر.unique())
print(filtered_data.iloc[:, 1].value_counts())

Number of bohor : 11
['البسيط' 'الخفيف' 'المجتث' 'المتدارك' 'السريع' 'الرمل' 'الوافر' 'الكامل'
 'المنسرح' 'الرجز' 'الطويل']
الطويل      68601
الكامل      50574
البسيط      37003
الوافر      23238
الخفيف      17984
السريع       9075
الرجز        7638
الرمل        6662
المنسرح      4375
المجتث       2085
المتدارك      380
Name: البحر, dtype: int64


In [10]:
filtered_data[0:10]

البيت   البحر
0  حاشا اهتمامك من إسداء مكرمة وأن يرى لك بين الن...  البسيط
1  دع مقصراً ليس بدَّاعاً ولا عجبٌ للأريحية والإح...  البسيط
2  أَيَّتُها النَفسُ لا تُهالي شَرخي قَد مَرَّ وَ...  البسيط
3  لَم يَبقَ إِلّا شَفاً يَسيرٌ قَرَّبَ مِن مَورِ...  البسيط
4  وَاِبتَهَلَ الدَهرُ في أَذاتي وَكانَ في الباطِ...  البسيط
5  وَأُمُّ دَفرٍ فَتاةُ سوءٍ تَخبُؤُني في ثَرىً م...  البسيط
6  مُرسِلَةً غارَةً بِخَيلٍ قَد غَنِيَت عَن هَبٍ ...  البسيط
7  وَجَدتُ حُبّي لَها قَديماً وَقَد تَبَيَّنتُ مَ...  البسيط
8  من سَرَّهُ كسبُ مالٍ لا نفاذَ له وراحةٌ قُرِنت...  البسيط
9  فلا يَمُدَّنَّ عينيه إلى سبب سوى القَناعة من م...  البسيط

In [11]:
filtered_data['البيت'] = filtered_data['البيت'].apply(pyarabic.araby.strip_tatweel)
#filtered_data = filtered_data.apply(pyarabic.araby.strip_tatweel)

In [12]:
import h5py

def save(nameOfFile,nameOfDataset,dataVar):
    h5f = h5py.File(nameOfFile, 'w')
    h5f.create_dataset(nameOfDataset, data=dataVar)
    h5f.close()


C:\Users\Ali\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


# Encoding Bohor

In [16]:
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(list(filtered_data["البحر"]))
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
bohor_encoded = onehot_encoder.fit_transform(integer_encoded)

In [17]:
some_values

['البسيط', 'الخفيف', 'السريع', 'الرمل', 'الوافر', 'الكامل', 'الرجز', 'الطويل']

In [18]:
bohor_encoded[150000]
integer_encoded[150000]

array([2], dtype=int64)

In [19]:
filtered_data.iloc[150000]

البيت    يَا رَبِّ أَصْلِحْنِي فَقَدْ فَسَدْتُ يَا رَبّ...
البحر                                                الرجز
Name: 156840, dtype: object

In [20]:
print(bohor_encoded.shape)
print(bohor_encoded)
#save('Y_Meters_Without_LowerClasses_OldData.h5', 'Y', bohor_encoded)

type(bohor_encoded)

(220775, 8)
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


numpy.ndarray

# Encoding Abyat

In [13]:
#data_without_Tashkeel = filtered_data['البيت'].apply(pyarabic.araby.strip_tashkeel)
data_with_Tashkeel = filtered_data['البيت']

In [14]:
data_with_Tashkeel

0         حاشا اهتمامك من إسداء مكرمة وأن يرى لك بين الن...
1         دع مقصراً ليس بدَّاعاً ولا عجبٌ للأريحية والإح...
2         أَيَّتُها النَفسُ لا تُهالي شَرخي قَد مَرَّ وَ...
3         لَم يَبقَ إِلّا شَفاً يَسيرٌ قَرَّبَ مِن مَورِ...
4         وَاِبتَهَلَ الدَهرُ في أَذاتي وَكانَ في الباطِ...
5         وَأُمُّ دَفرٍ فَتاةُ سوءٍ تَخبُؤُني في ثَرىً م...
6         مُرسِلَةً غارَةً بِخَيلٍ قَد غَنِيَت عَن هَبٍ ...
7         وَجَدتُ حُبّي لَها قَديماً وَقَد تَبَيَّنتُ مَ...
8         من سَرَّهُ كسبُ مالٍ لا نفاذَ له وراحةٌ قُرِنت...
9         فلا يَمُدَّنَّ عينيه إلى سبب سوى القَناعة من م...
10        فيال لها رتبة جَلَّت بلا طلبٍ ولا حسود ولا ذل ...
11        إن الخليط أجدِّ البين فابتكروا لنية ثم ما عاجو...
12        زمّوا الجمال وقالوا إن مشربكم ماء بكيلة لا ملح...
13        ما كان بينهم إلا مجاهرة أشفقت منها فماذا زادك ...
14        استقبلوا المسقط الشرقي يحفزهم في السير أشوَس م...
15         كأن ظعنهم والآل يرفعها نخل المشقر أو ما زينت هجر
16        ما زلت أرمقهم في الال مرتفعا ح

In [15]:
data_with_Tashkeel.shape

(227615,)

In [16]:
maximum_bayt_len = np.max((data_with_Tashkeel.apply(helpers.separate_token_with_dicrites).apply(len)))
maximum_bayt_len

82

In [17]:
#encoded_byot = data_with_Tashkeel.apply(lambda x: helpers.string_with_tashkeel_vectorizer(x, maximum_bayt_len))
encoded_byot = data_with_Tashkeel.apply(lambda x: helpers.string_with_tashkeel_vectorizer_OneHot(x, maximum_bayt_len))
len(encoded_byot[1])

82

In [18]:
encoded_byot[1].shape

(82, 183)

In [21]:
encoded_byot[1]
encoded_byot.shape
print(data_with_Tashkeel[100])

بظلمة الظلمِ يوم أعلوا رأسي حسينٍ على الرديني


In [22]:
# Reshaping the heck!!
reshaped_data_matrix_with_tashkeel = np.stack(encoded_byot, axis=0)
#reshaped_data_matrix_without_tashkeel = np.stack(encoded_byot[0:1000000], axis=0)

In [23]:
# Dimensions
reshaped_data_matrix_with_tashkeel

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

# Saving Abyat

In [24]:
save('old_data_matrix_with_tashkeel_OneHotEncodingWithTashkeel.h5', 'X', reshaped_data_matrix_with_tashkeel)

In [25]:
encoded_byot.shape

(227615,)

In [27]:
X = np.array(encoded_byot)
X[1].shape

(82, 183)

In [57]:
nono = encoded_byot.as_matrix()
np.stack(nono)

array([[[0, 0, 0, ..., 1, 0, 1],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 1, ..., 1, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 1, 1, 0],
        [0, 0, 0, ..., 0, 1, 1],
        [0, 0, 0, ..., 0, 1, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 1, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 1, 1, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 1, 1],
        ...,
        [0, 0, 0, ..., 

In [58]:
test = encoded_byot

In [59]:
test = test[0:2]
test

0    [[0, 0, 0, 0, 0, 1, 0, 1], [0, 0, 0, 0, 0, 0, ...
1    [[0, 0, 0, 0, 0, 1, 1, 1], [0, 0, 0, 1, 0, 0, ...
Name: البيت, dtype: object

In [60]:
resualt = np.stack(test, axis=0)
print(resualt.shape)
print(resualt)

(2, 82, 8)
[[[0 0 0 ... 1 0 1]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 1 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 1 1 1]
  [0 0 0 ... 0 0 1]
  [0 0 1 ... 1 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [64]:
bayt_encoded_without_tashkeel

0         [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
1         [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
2         [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
3         [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
4         [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
5         [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
6         [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
7         [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
8         [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
9         [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
10        [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
11        [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
12        [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
13        [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
14        [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
15        [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
16        [[0, 0, 0, 0, 0, 0, 0, 1], [0,