In [1]:
import pandas as pd
import arabic
import pyarabic
import helpers
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
#########################
from numpy import array, argmax
import numpy as np
import re
##########################

In [10]:
old_data_flag = 0 # 1 only if old data, 0 otherwise
input_data_path = "../data/Almoso3a_Alshe3rya/data/All_ksaied.csv"

In [11]:
if (old_data_flag == 1):
    data = pd.read_csv('All_OldData_cleaned.csv', index_col=0)
    print("working into old data sample ")
    cols = [1,2,4]
    data.drop(data.columns[cols], axis=1,inplace=True)
    data.columns = ['البيت', 'البحر']
    our_alphabets = "".join(arabic.alphabet) + "".join(arabic.tashkeel)+" "
    our_alphabets = "".join(our_alphabets)
    data['البيت'] = data['البيت'].apply(lambda x: re.sub(r'[^'+our_alphabets+']','',str(x))).apply(lambda x: re.sub(r'  *'," ",x)).apply(lambda x: re.sub(r'ّ+', 'ّ', x)).apply(lambda x: x.strip())
    #data['البيت'] = data['البيت'].apply(pyarabic.araby.strip_tashkeel).apply(pyarabic.araby.strip_tatweel)
elif (old_data_flag == 0):
    print("working on new data sample")
    data = pd.read_csv(input_data_path, index_col=0)
    bahr = 'البحر'
    bayt = 'البيت'
    data  = data[[bayt, bahr]]
    our_alphabets = "".join(arabic.alphabet) + "".join(arabic.tashkeel)+" "
    our_alphabets = "".join(our_alphabets)
    data['البيت'] = data['البيت'].apply(lambda x: re.sub(r'[^'+our_alphabets+']','',str(x))).apply(lambda x: re.sub(r'  *'," ",x)).apply(lambda x: re.sub(r'ّ+', 'ّ', x)).apply(lambda x: x.strip())
    #data['البيت'] = data['البيت'].apply(pyarabic.araby.strip_tashkeel).apply(pyarabic.araby.strip_tatweel)


working on new data sample


C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\arraysetops.py:395: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


In [12]:
data.columns

Index(['البيت', 'البحر'], dtype='object')

In [13]:
bahr = 'البحر'
bayt = 'البيت'
data  = data[[bayt, bahr]]
data.shape

(1831770, 2)

In [14]:
data.iloc[:, 1].value_counts()

الطويل          405378
الكامل          363486
البسيط          239974
الخفيف          156049
الوافر          140560
الرجز           117572
&nbsp;           92334
الرمل            79015
المتقارب         63818
السريع           58084
موشح             30060
المنسرح          28357
المجتث           17884
المديد            7829
الهزج             7541
عامي              7074
المتدارك          5037
شعر التفعيلة      3232
الدوبيت           2713
شعر حر            2135
المواليا          1644
السلسلة            907
المقتضب            799
المضارع            288
Name: البحر, dtype: int64

# Getting Unique Bohor

In [16]:
classic_bohor = list(data.البحر.unique()[0:11])
classic_bohor= ['الطويل'
,'الكامل'
,'البسيط'
,'الخفيف'
,'الوافر'
,'الرجز'
,'الرمل'
,'المتقارب'
,'السريع'
,'المنسرح'
,'المجتث'
,'المديد'
,'الهزج'
,'المتدارك'
,'المقتضب'
,'المضارع']

# Filtering Data

In [18]:
#some_values = ['البسيط','الخفيف','السريع','الرمل','الوافر','الكامل','الرجز','الطويل']
#filtered_data = data.loc[data['البحر'].isin(some_values)]
filtered_data = data.loc[data['البحر'].isin(classic_bohor)]
filtered_data.iloc[:, 1].value_counts()
filtered_data.shape

(1691671, 2)

In [9]:
# TESTING
print("Number of bohor : "+str(len(filtered_data.البحر.unique())))
print(filtered_data.البحر.unique())
print(filtered_data.iloc[:, 1].value_counts())

Number of bohor : 11
['البسيط' 'الخفيف' 'المجتث' 'المتدارك' 'السريع' 'الرمل' 'الوافر' 'الكامل'
 'المنسرح' 'الرجز' 'الطويل']
الطويل      68601
الكامل      50574
البسيط      37003
الوافر      23238
الخفيف      17984
السريع       9075
الرجز        7638
الرمل        6662
المنسرح      4375
المجتث       2085
المتدارك      380
Name: البحر, dtype: int64


In [19]:
filtered_data[0:10]

البيت   البحر
0  خَليلَيَّ لا تَستَعجِلا أَن تَزَوَّدا وَأَن تَ...  الطويل
1  فَما لَبَثٌ يَوماً بِسابِقٍ مَغنَمٍ وَلا سُرعَ...  الطويل
2  وَإِن تُنظِراني اليَومَ أَقضِ لُبانَةً وَتَستَ...  الطويل
3  لَعَمرُكَ ما نَفسٌ بِجِدٍ رَشيدَةٍ تُؤامِرُني ...  الطويل
4  وَإِن ظَهَرَت مِنهُ قَوارِصُ جَمَّةٌ وَأَفرَعَ...  الطويل
5  عَلى غَيرِ ذَنبٍ أَن أَكونَ جَنَيتُهُ سِوى قَو...  الطويل
6  لَعَمري لَنِعمَ المَرءُ تَدعو بِحَبلِهِ إِذا م...  الطويل
7  عَظيمُ رَمادِ القِدرِ لا مُتَعَبِّسٌ وَلا مُؤي...  الطويل
8  وَإِن صَرَّحَت كَحلٌ وَهَبَّت عَرِيَّةٌ مِنَ ا...  الطويل
9  صَبَرتُ عَلى وَطءِ المَوالي وَحَطمِهِم إِذا ضَ...  الطويل

In [11]:
filtered_data['البيت'] = filtered_data['البيت'].apply(pyarabic.araby.strip_tatweel)
#filtered_data = filtered_data.apply(pyarabic.araby.strip_tatweel)

In [12]:
import h5py

def save(nameOfFile,nameOfDataset,dataVar):
    h5f = h5py.File(nameOfFile, 'w')
    h5f.create_dataset(nameOfDataset, data=dataVar)
    h5f.close()


C:\Users\Ali\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


# Encoding Bohor

In [20]:
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(list(filtered_data["البحر"]))
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
bohor_encoded = onehot_encoder.fit_transform(integer_encoded)

In [25]:
label_encoder.shape

AttributeError: 'LabelEncoder' object has no attribute 'shape'

In [18]:
bohor_encoded[150000]
integer_encoded[150000]

array([2], dtype=int64)

In [19]:
filtered_data.iloc[150000]

البيت    يَا رَبِّ أَصْلِحْنِي فَقَدْ فَسَدْتُ يَا رَبّ...
البحر                                                الرجز
Name: 156840, dtype: object

In [20]:
print(bohor_encoded.shape)
print(bohor_encoded)
#save('Y_Meters_Without_LowerClasses_OldData.h5', 'Y', bohor_encoded)

type(bohor_encoded)

(220775, 8)
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


numpy.ndarray

# Encoding Abyat

In [13]:
#data_without_Tashkeel = filtered_data['البيت'].apply(pyarabic.araby.strip_tashkeel)
data_with_Tashkeel = filtered_data['البيت']

In [14]:
data_with_Tashkeel

0         حاشا اهتمامك من إسداء مكرمة وأن يرى لك بين الن...
1         دع مقصراً ليس بدَّاعاً ولا عجبٌ للأريحية والإح...
2         أَيَّتُها النَفسُ لا تُهالي شَرخي قَد مَرَّ وَ...
3         لَم يَبقَ إِلّا شَفاً يَسيرٌ قَرَّبَ مِن مَورِ...
4         وَاِبتَهَلَ الدَهرُ في أَذاتي وَكانَ في الباطِ...
5         وَأُمُّ دَفرٍ فَتاةُ سوءٍ تَخبُؤُني في ثَرىً م...
6         مُرسِلَةً غارَةً بِخَيلٍ قَد غَنِيَت عَن هَبٍ ...
7         وَجَدتُ حُبّي لَها قَديماً وَقَد تَبَيَّنتُ مَ...
8         من سَرَّهُ كسبُ مالٍ لا نفاذَ له وراحةٌ قُرِنت...
9         فلا يَمُدَّنَّ عينيه إلى سبب سوى القَناعة من م...
10        فيال لها رتبة جَلَّت بلا طلبٍ ولا حسود ولا ذل ...
11        إن الخليط أجدِّ البين فابتكروا لنية ثم ما عاجو...
12        زمّوا الجمال وقالوا إن مشربكم ماء بكيلة لا ملح...
13        ما كان بينهم إلا مجاهرة أشفقت منها فماذا زادك ...
14        استقبلوا المسقط الشرقي يحفزهم في السير أشوَس م...
15         كأن ظعنهم والآل يرفعها نخل المشقر أو ما زينت هجر
16        ما زلت أرمقهم في الال مرتفعا ح

In [15]:
data_with_Tashkeel.shape

(227615,)

In [16]:
maximum_bayt_len = np.max((data_with_Tashkeel.apply(helpers.separate_token_with_dicrites).apply(len)))
maximum_bayt_len

82

In [17]:
#encoded_byot = data_with_Tashkeel.apply(lambda x: helpers.string_with_tashkeel_vectorizer(x, maximum_bayt_len))
encoded_byot = data_with_Tashkeel.apply(lambda x: helpers.string_with_tashkeel_vectorizer_OneHot(x, maximum_bayt_len))
len(encoded_byot[1])

82

In [18]:
encoded_byot[1].shape

(82, 183)

In [21]:
encoded_byot[1]
encoded_byot.shape
print(data_with_Tashkeel[100])

بظلمة الظلمِ يوم أعلوا رأسي حسينٍ على الرديني


In [22]:
# Reshaping the heck!!
reshaped_data_matrix_with_tashkeel = np.stack(encoded_byot, axis=0)
#reshaped_data_matrix_without_tashkeel = np.stack(encoded_byot[0:1000000], axis=0)

In [23]:
# Dimensions
reshaped_data_matrix_with_tashkeel

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

# Saving Abyat

In [24]:
save('old_data_matrix_with_tashkeel_OneHotEncodingWithTashkeel.h5', 'X', reshaped_data_matrix_with_tashkeel)

In [25]:
encoded_byot.shape

(227615,)

In [27]:
X = np.array(encoded_byot)
X[1].shape

(82, 183)

In [57]:
nono = encoded_byot.as_matrix()
np.stack(nono)

array([[[0, 0, 0, ..., 1, 0, 1],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 1, ..., 1, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 1, 1, 0],
        [0, 0, 0, ..., 0, 1, 1],
        [0, 0, 0, ..., 0, 1, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 1, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 1, 1, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 1, 1],
        ...,
        [0, 0, 0, ..., 

In [58]:
test = encoded_byot

In [59]:
test = test[0:2]
test

0    [[0, 0, 0, 0, 0, 1, 0, 1], [0, 0, 0, 0, 0, 0, ...
1    [[0, 0, 0, 0, 0, 1, 1, 1], [0, 0, 0, 1, 0, 0, ...
Name: البيت, dtype: object

In [60]:
resualt = np.stack(test, axis=0)
print(resualt.shape)
print(resualt)

(2, 82, 8)
[[[0 0 0 ... 1 0 1]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 1 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 1 1 1]
  [0 0 0 ... 0 0 1]
  [0 0 1 ... 1 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [64]:
bayt_encoded_without_tashkeel

0         [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
1         [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
2         [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
3         [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
4         [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
5         [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
6         [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
7         [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
8         [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
9         [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
10        [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
11        [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
12        [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
13        [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
14        [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
15        [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, ...
16        [[0, 0, 0, 0, 0, 0, 0, 1], [0,

In [3]:
import helpers 
import pandas as pd

In [4]:
d = pd.read_csv('../../../data/All_clean_data.csv')

/home/moroclash/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (1,3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [ ]:
helpers.Clean_data(d,84)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064
2065
2066
2067
2068
2069
2070
2071
2072
2073
2074
2075
2076
2077
2078
2079
2080
2081
2082
2083
2084
2085
2086
2087
2088
2089
2090
2091


3583
3584
3585
3586
3587
3588
3589
3590
3591
3592
3593
3594
3595
3596
3597
3598
3599
3600
3601
3602
3603
3604
3605
3606
3607
3608
3609
3610
3611
3612
3613
3614
3615
3616
3617
3618
3619
3620
3621
3622
3623
3624
3625
3626
3627
3628
3629
3630
3631
3632
3633
3634
3635
3636
3637
3638
3639
3640
3641
3642
3643
3644
3645
3646
3647
3648
3649
3650
3651
3652
3653
3654
3655
3656
3657
3658
3659
3660
3661
3662
3663
3664
3665
3666
3667
3668
3669
3670
3671
3672
3673
3674
3675
3676
3677
3678
3679
3680
3681
3682
3683
3684
3685
3686
3687
3688
3689
3690
3691
3692
3693
3694
3695
3696
3697
3698
3699
3700
3701
3702
3703
3704
3705
3706
3707
3708
3709
3710
3711
3712
3713
3714
3715
3716
3717
3718
3719
3720
3721
3722
3723
3724
3725
3726
3727
3728
3729
3730
3731
3732
3733
3734
3735
3736
3737
3738
3739
3740
3741
3742
3743
3744
3745
3746
3747
3748
3749
3750
3751
3752
3753
3754
3755
3756
3757
3758
3759
3760
3761
3762
3763
3764
3765
3766
3767
3768
3769
3770
3771
3772
3773
3774
3775
3776
3777
3778
3779
3780
3781
3782
